const ACTION_TYPES = {
  APP: {
    FETCH_DATA: "FETCH_DATA",
    FETCH_DATA_SUCCESS: "FETCH_DATA_SUCCESS",
    FETCH_DATA_ERROR: "FETCH_DATA_ERROR"
  },
  ORDER: {
    SET_BURGER: "SET_BURGER",
    CONFIGURE_BURGER: "CONFIGURE_BURGER"
  }
};

export default ACTION_TYPES;
